#include "EZVisual/Interfaces/Backgroundable.h"
#include "EZVisual/Interfaces/Childrenable.h"
#include "EZVisual/Interfaces/Marginable.h"
#include "EZVisual/Interfaces/Orientationable.h"
#include "EZVisual/Interfaces/Paddingable.h"
#include "EZVisual/Interfaces/Textable.h"
#include "EZVisual/Interfaces/Contentable.h"
#include "EZVisual/Interfaces/VisualElement.h"