#include "EZVisual/Interfaces/Backgroundable.hpp"
#include "EZVisual/Interfaces/Childrenable.hpp"
#include "EZVisual/Interfaces/Marginable.hpp"
#include "EZVisual/Interfaces/Orientationable.hpp"
#include "EZVisual/Interfaces/Paddingable.hpp"
#include "EZVisual/Interfaces/Textable.hpp"
#include "EZVisual/Interfaces/Contentable.hpp"
#include "EZVisual/Interfaces/VisualElement.h"